### ISSUE TITLE
The 3D-DNA final results get more fragment than before

### ISSUE THREAD

**Issue by Lillian-21** [aidenlab/3d-dna#98] opened 2020-11-26 03:08 UTC
I have a 430M nanopore assembly results with 83 contigs but it becomes more fragment with 400 contigs after 3D-DNA assembly. I want to know how to improve my row assembly with HIC data (just with default parameters). Thanks.

**Comment by dudcha** [comment] 2020-12-04 15:01
Closing since not a bug. Note a few things: Number of contigs doesn't mean much. Its the distribution of sizes that is important. You have maps that are built to check if the results you are getting are meaningful and if not what might be the problem: is it the data, is it the assembly, is it the algorithm performance. Check your 0.hic. Check the tracks to see if the misjoin correction is working as expected. I recommend checking discussions on this on aidenlab.org/forum.html. Best, -Olga

**Closed as completed by dudcha** 2020-12-04 15:01 UTC
