### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007effb0a00000, 17179869184, 0) failed; error='Cannot allocate memory' (errno=12)

### ISSUE THREAD

**Issue by wuxiaopei0509** [aidenlab/3d-dna#65] opened 2019-10-17 08:41 UTC
when I run the pipeline ,it occured :
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007effb0a00000, 17179869184, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 17179869184 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /1data/wuxiaopei/Jucier_3dDNA/3d-dna_results/hs_err_pid29362.log
:( No resolved files are found. Please rerun the pipeline to include the scaffold segment. Exiting!
what's the problem?How can I slove it ?

**Comment by dudcha** [comment] 2019-10-17 16:45
Hello wuxiaopei0509,

Seems your machine does not have enough memory for the job. Allocate more memory to the task, if you can afford it. A typical .hic file creation needs something on the scale of 128Gb.

Closing since this is not a bug.

Thanks,
Olga

**Closed as completed by dudcha** 2019-10-17 16:45 UTC
