### ISSUE TITLE
the difference between diploid and haplotig mode

### ISSUE THREAD

**Issue by leeun67** [aidenlab/3d-dna#84] opened 2020-08-06 02:35 UTC
hi,thanks for you create the beautiful tool,and i want to know  the difference between diploid and haplotig mode,and my species is high heterozygous  ,what should i choose after i use the purge_haplotig remove the heterozygous?

**Comment by dudcha** [comment] 2020-08-06 03:48
Hey leeun67,

Thanks for the kind words. The haploid mode it doing some post-processing trying to merge alternative haplotypes if present in the assembly. Some details on this can be found in Dudchenko et al., 2017 in supplement. Also see some detailed discussion of this here: https://github.com/theaidenlab/AGWG-merge.

You typically want to run default, haploid. Check the assembled maps for signal associated with undercollapsed heterozygosity (see agwg-merge) and then decide if you need a haploid mode.

Hope this helps and closing since not a bug. Consider posting to aidenlab.org/forum.html for generate usage inquiries. Thanks!

Olga

**Closed as completed by dudcha** 2020-08-06 03:48 UTC
