### ISSUE TITLE
Why the 3ddna results  were not consistent with my genetic linkage map?

### ISSUE THREAD

**Issue by baishengjun** [aidenlab/3d-dna#118] opened 2021-05-17 02:42 UTC
Hi,

After I use 3ddna to generate my genome, I find it does not consistent with my genetic linkage map. 
The following image shows the relationship between my genome and the genetic linkage map.  and additional 3 chromosomes were also in the same phenomenon.
Should I adjust it to consist with my genetic linkage map?  and why 3ddna result in this problem?
![image](https://user-images.githubusercontent.com/55916074/118425230-54c25300-b6fb-11eb-967a-99353a20eed7.png)

Thanks,
Bai

**Comment by dudcha** [comment] 2021-05-26 04:58
Hello Bai,

Closing since this is not a bug, but going to comment. 3D-DNA scaffolds things together based on the intensity of 3D contact. In your case my guess is that 2 things are happening: 1) the contact frequency between telomeres in your species is high (often observed in plants and in diptera, other things that are in the Rabl nuclear configuration) and 2) sequences from the centromere are not contributing as expected due to either a) not getting assembled properly or b) getting assembled but being repetitive enough that the aligner cannot map the HI-C reads to them with mapping quality >=1. Understanding the source should help you address, either by working with the mapping threshold, or examining your contig set, etc. It is also very easy to address in JBAT.

Best,
Olga

**Closed as completed by dudcha** 2021-05-26 04:58 UTC
