### ISSUE TITLE
Some strange fragments on a chromosome

### ISSUE THREAD

**Issue by StevenBai97** [aidenlab/3d-dna#116] opened 2021-04-17 07:56 UTC
Hi, 
I used hifisam to assemble a genome and got a great result (N50: 5.4Mb, BUSCO: 98.6%). However, I have some confusion about the Hi-C scaffolding result (image1) after running 3d-dna and juicebox. As shown in the picture, chr10 has some fragments. (image2) I don't know the reason. Could you please give me some suggestions? Thanks for a lot.
![image1](https://user-images.githubusercontent.com/80459240/115106099-69dd8200-9f95-11eb-8cd5-882dead0eb65.png)
![image2](https://user-images.githubusercontent.com/80459240/115106100-6cd87280-9f95-11eb-8073-8dfe97fc5d42.png)

**Comment by dudcha** [comment] 2021-04-29 22:28
Hello Steven, Looks like some repeat-driven rearrangements in a plant (?) cenromeric region. My advice woudl be to play with this in JBAT. There's nothing I can do just looking at the picture, sorry. Closing since this is not a bug. Thanks, -Olga

**Closed as completed by dudcha** 2021-04-29 22:28 UTC
