### ISSUE TITLE
how to generate 'FINAL' assembly/hic files

### ISSUE THREAD

**Issue by egoltsman** [aidenlab/3d-dna#83] opened 2020-07-07 23:02 UTC
Hello,
I'm wondering if you can help me understand the final outputs of the workflow.
I ran the 3ddna.sh pipeline,  then reviewed/edited in juicebox, then ran the post-review steps as follows:

run-asm-pipeline-post-review.sh -r my.review.assembly  /path/to/merged_nodups.txt

At the end, the 'FINAL.fasta' file contains the most contiguous assembly, and that's what I'm using for further analysis.  Now I'd like to go back to the .hic file in juicebox and look at it in the context of this FINAL assembly.  However, there is no .assembly  file with corresponding scaffold names that I can load.    Is it possible to derive a mapping of sorts between the names in the 'FINAL' file and those produced prior to the call to 'finalize-output.sh",  i.e. the ".final.*" files ?

Thank you!

**Comment by egoltsman** [comment] 2020-07-15 21:50
Hello again,
While waiting for your reply I went ahead and mapped the 'final' contigs, to the 'FINAL' gapped scaffolds using minimap2.  That produced something of a map that I can use,   but what would really make it easier is if it was possible to generate a new .assembly file that could be used to make the 'FINAL.hic'  file for visualization.  According to the README, 
```
[.assembly files] are available for all stages of the assembly including:
* “FINAL“ - after the addition of gaps to the chromosome-length assembly;
```

But I suspect that this is true only for the automated end-to-end pipeline and not for the  run-asm-pipeline-post-review.sh

**Comment by dudcha** [comment] 2020-07-15 21:56
Hey Eugene,
I'm sorry, looks like I've missed this thread. Generally speaking, since this is not a bug discussion it would be much better to move this to aidnelab.org/forum.html (also DNA Zoo forum).
You can make the FINAL.hic (still in assembly format) by passing the --build-gapped-map flag. In the next release there will be also an option to generate the sandboxed hic file with data sandboxed to chromosomes only. Do I understand correctly that you are essentially looking to build the .FINAL.assembly? This is going to be available in the next release, eta a few weeks. Note that while you can use it for remapping, you cant' use it with Juicebox Assembly Tools.
Best, -Olga

**Comment by dudcha** [comment] 2020-07-15 21:56
Also closing since not a bug.

**Closed as completed by dudcha** 2020-07-15 21:56 UTC

**Comment by egoltsman** [comment] 2020-07-15 22:34
Hi Olga,
Sorry, I will post questions like this on the forum from no on.     The --build-gapped-map flag is not part of the  run-asm-pipeline-post-review.sh pipeline or any of its sub-steps.    Or is there another workflow I should be running at the end?

**Comment by dudcha** [comment] 2020-07-15 22:46
Are you sure you are looking at the last release? 

--build-gapped-map

I can see this In the post-review

Olga

**Comment by egoltsman** [comment] 2020-07-15 23:11
No :(   Thank you for the heads up.
